services:
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    
  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
  
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"